name: flutter_base_architecture
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+0
# You just need to type "flutter pub run build_runner build --delete-conflicting-outputs" in Terminal, then press Enter :)))

environment:
  sdk: ">=2.12.0 <4.0.0"
dependency_overrides:
  # qr_code_scanner:
  #   git:
  #     url: https://github.com/X-SLAYER/qr_code_scanner.git
  #     ref: flutter-beta
  # camera_android:
  #   git:
  #     url: https://github.com/bottlepay/plugins.git
  #     path: packages/camera/camera_android
  #     ref: e1a4dba770da9bc3cf9f858bac6837083f8b9059
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.3
  dio: ^5.3.2
  json_annotation: ^4.0.1
  retrofit: any
  copy_with_extension: ^5.0.2
  responsive_framework: ^1.0.0
  tuple: ^2.0.0
  get: ^4.6.1
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.5
  shared_preferences: ^2.0.7
  location: ^5.0.3
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.1.0
  fluttertoast: ^8.0.8
  html: ">=0.15.0 <1.0.0"
  csslib: ^1.0.0
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.11
  bot_toast: ^4.0.1
  flutter_easyloading: ^3.0.3
  image_picker: ^1.0.4
  android_intent: ^2.0.2
  package_info: ^2.0.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^16.3.0
  open_file_plus: ^3.4.1
  lottie: ^2.3.2
  camera: ^0.10.5+2
  flutter_google_location_picker: ^0.0.3
  geolocator: ^10.0.1
  firebase_auth: ^4.9.0
  http: ^0.13.5
  connectivity_plus: ^2.3.9
  google_fonts: ^4.0.4
  upgrader: ^6.5.0
  flutter_localization: ^0.1.14
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  pinput: ^3.0.1
  device_info: ^2.0.3
  file_picker: ^5.2.10
  responsive_builder: ^0.7.0
  device_uuid: ^0.0.4
  appcheck: ^1.0.6
  external_app_launcher: ^3.1.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  build_resolvers: ^2.4.0
  retrofit_generator: ^8.0.6
  json_serializable: 6.6.2
  copy_with_extension_gen: ^5.0.4
  # dart run build_runner build
  flutter_launcher_icons: ^0.13.1

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_app.png"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: UTM-Aptima
      fonts:
        - asset: assets/fonts/UTM-Aptima.ttf
        - asset: assets/fonts/UTM-Aptima-Bold.ttf
          weight: 700
